#even 
Guidelines:
A = 1
2-10
J = 11
Q = 12
K = 13

Suites:
1 -4

Diamond: 1
Spades: 2
Hearts: 3
clubs: 4


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

KeyboardInterrupt: ignored

In [ ]:
# import numpy as np
# aggregation_rules = np.array([])
aggregation_rules = []

In [ ]:
aggregation_rules = []

import pandas as pd
import numpy as np
from numpy import asarray
from numpy import savetxt
from sklearn.preprocessing import OneHotEncoder
import random
master = []

# default = 2
# bad = 1
# good = 3

for i in range(100):
  deck = []
  deck.clear()


  # creating instance of one-hot-encoder
  enc = OneHotEncoder(handle_unknown='ignore')
  counter = 0

  for suit in range (1,5):
    set = []
    for card_num in range (1,14):
      if card_num >10:
        face = 1
      else:
        face = 0
      if card_num%2 == 0:
        even = 3
      else:
        even = 2
      set.append([card_num,suit,face,even])
      counter+=1
    deck.extend(set)


  deck_duplicate = list.copy(deck)

  multiple = []
  multiple.clear()

  for i in range(30):
    multiple.append(random.choice(deck_duplicate))
    deck_duplicate.remove(multiple[-1])


  for j in range (len(multiple)):
    if multiple[j][3] == 2:
      multiple[j][3] = 1


  for note in deck_duplicate:
    note[3] = 2

  multiple.extend(deck_duplicate)

  # counter1 = 0
  # counter2 =0
  # counter3 = 0

  # for index in multiple:
  #   if index[3] == 1:
  #     counter_1 +=1
  #   if index[3] == 2:
  #     counter_2 += 1
  #   else:
  #     counter_3 +=1

  # print(counter1)
  # print(counter2)
  # print(counter3)

  # print(multiple)


  enc.fit(multiple)
  

  aggregation_rules.append(enc.transform(multiple).toarray())


# print(len(aggregation_rules))

master = []
for i in range(100):
  aggregation_rules


df = pd.DataFrame(aggregation_rules[0])
df = pd.DataFrame(aggregation_rules[1])
df = pd.DataFrame(aggregation_rules[0])
df = pd.DataFrame(aggregation_rules[0])
df = pd.DataFrame(aggregation_rules[0])
df = pd.DataFrame(aggregation_rules[0])

# df = df.drop([17],axis=1)

# df
# # df.reset_index(drop=True, inplace=True)
# type(aggregation_rules)


# convert list to ndarray 


# a = np.asarray(master) 

# #np.append([[3,2]],axis = 0)

# # aggregation_rules.append([3,2],axis = 0)
# np.append([a,[3,2]],axis = 0)

#aggregation_rules.append([master])
    


aggregation_rules = aggregation_rules[0:102]
len(aggregation_rules[0])
df



0    1    2    3    4    5    6   ...   15   16   17   18   19   20   21
0   0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  0.0  0.0  1.0
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  0.0  1.0
2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0  1.0  0.0  0.0  1.0
3   0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  1.0  1.0  0.0  0.0  0.0  1.0
4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  1.0
5   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  1.0  0.0  0.0
6   0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  1.0  0.0  0.0
8   0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0
9   0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  1.0
11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  1.0  0.0  0.0  1.0
12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  1.0  0.0  0.0
13  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0  1.0  0.0  1.0  0.0  0.0
14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  0.0  0.0  1.0
15  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  0.0  0.0  1.0
16  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0
17  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0
18  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  1.0
19  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0
20  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  1.0  0.0  0.0
21  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  0.0  0.0  1.0
22  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
23  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
24  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  0.0  0.0  1.0
25  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0  1.0  1.0  0.0  0.0
26  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0
27  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  1.0
28  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  1.0
29  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0
30  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
32  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
33  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  0.0  1.0  0.0
34  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
35  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
36  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
37  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
38  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  0.0  1.0  0.0
39  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  1.0  0.0
40  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  1.0  0.0
41  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  1.0  0.0
42  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  1.0  0.0
43  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  1.0  0.0
44  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  1.0  0.0
45  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0  1.0  0.0  1.0  0.0
46  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  0.0  1.0  0.0
47  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  0.0  1.0  0.0
48  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  0.0  1.0  0.0
49  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  1.0  1.0  0.0  0.0  1.0  0.0
50  0.0  0.0  0.0  0.0  0.0

In [ ]:
df.sum(axis=0)

0      4.0
1      4.0
2      4.0
3      4.0
4      4.0
5      4.0
6      4.0
7      4.0
8      4.0
9      4.0
10     4.0
11     4.0
12     4.0
13    13.0
14    13.0
15    13.0
16    13.0
17    40.0
18    12.0
19    16.0
20    22.0
21    14.0
dtype: float64

In [ ]:
df = pd.DataFrame(aggregation_rules[0]).drop([17],axis=1)
# df1 = pd.DataFrame(aggregation_rules[1]).drop([17],axis=1)



df2 = df.iloc[0,:].to_frame().transpose()

for i in range(1,52):
  df3 = df.iloc[i,:].to_frame().transpose()
  df2.reset_index(drop=True, inplace=True)
  df3.reset_index(drop=True, inplace=True)
  df2 = pd.concat([df2,df3],axis=1)
df37 = df2
df37
# print(df1)

0    1    2    3    4    5    6   ...   14   15   16   18   19   20   21
0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0

[1 rows x 1092 columns]

In [ ]:

for j in range(100):
  df = pd.DataFrame(aggregation_rules[j]).drop([17],axis=1)
  # df1 = pd.DataFrame(aggregation_rules[1]).drop([17],axis=1)

  df2 = df.iloc[0,:].to_frame().transpose()

  for i in range(1,52):
    df3 = df.iloc[i,:].to_frame().transpose()
    df2.reset_index(drop=True, inplace=True)
    df3.reset_index(drop=True, inplace=True)
    df2 = pd.concat([df2,df3],axis=1)
  df38 = df2
  # df38
  # print(df1)
  df37 = pd.concat([df37,df38],axis=0)
df37

0    1    2    3    4    5    6   ...   14   15   16   18   19   20   21
0   0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0   0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0   0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0   0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0   0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0

[101 rows x 1092 columns]

In [ ]:
final_rule1 = df37.iloc[1:101,:]


0    1    2    3    4    5    6   ...   14   15   16   18   19   20   21
0   0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0   0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
0   0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0   0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0   0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0

[100 rows x 1092 columns]

In [ ]:
final_rule1.to_csv('final_rule1.csv')

In [ ]:
for j in range(100):
  df = pd.DataFrame(aggregation_rules[j]).drop([17],axis=1)

  for i in range(1,52):
    df3 = df.iloc[i,:].to_frame().transpose()
    df2.reset_index(drop=True, inplace=True)
    df3.reset_index(drop=True, inplace=True)
    df2 = pd.concat([df2,df3],axis=1)
df2
# print(df1)

In [ ]:
df5 = df37
for j in range(1,100):
  df2 = pd.DataFrame(aggregation_rules[j]).drop([17],axis=1)
  for i in range(1,52):
    df3 = df.iloc[i,:].to_frame().transpose()
    df2.reset_index(drop=True, inplace=True)
    df3.reset_index(drop=True, inplace=True)
    df2 = pd.concat([df2,df3],axis=1)
  df2.reset_index(drop=True, inplace=True)
  df5 = pd.concat([df5,df2],axis=0)
df5
# print(df1)

0    1    2    3    4    5    6   ...   14   15   16   18   19   20   21
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0   0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
1   0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
47  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
48  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
49  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
50  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
51  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[5097 rows x 1092 columns]

#Odd

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
aggregation_rules = []

for i in range(100):
  deck = []
 


  # creating instance of one-hot-encoder
  enc = OneHotEncoder(handle_unknown='ignore')
  counter = 0

  for suite in range (1,5):
    set = []
    for card_num in range (1,14):
      if card_num > 10:
        face = 1
      else:
        face = 0
      if card_num%2 == 1:
        odd = 3
      else:
        odd = 2
      set.append([card_num,suite,face,odd])
    deck.extend(set)


  deck_duplicate = list.copy(deck)

  multiple = []
  multiple.clear()

  for i in range(30):
    multiple.append(random.choice(deck_duplicate))
    deck_duplicate.remove(multiple[-1])

  for j in range (len(multiple)):
    if multiple[j][3] == 2:
      multiple[j][3] = 1



  for note in deck_duplicate:
    note[3] = 2

  multiple.extend(deck_duplicate)

  #print(multiple)


  enc.fit(multiple)
  

  aggregation_rules.append(enc.transform(multiple).toarray())

#print(master)
#aggregation_rules.append(master)   

print(aggregation_rules[0])


    







[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [ ]:
df = pd.DataFrame(aggregation_rules[0])
df.sum(axis=0)

0      4.0
1      4.0
2      4.0
3      4.0
4      4.0
5      4.0
6      4.0
7      4.0
8      4.0
9      4.0
10     4.0
11     4.0
12     4.0
13    13.0
14    13.0
15    13.0
16    13.0
17    40.0
18    12.0
19    11.0
20    22.0
21    19.0
dtype: float64

In [ ]:
df = pd.DataFrame(aggregation_rules[0]).drop([17],axis=1)

df2 = df.iloc[0,:].to_frame().transpose()

for i in range(1,52):
  df3 = df.iloc[i,:].to_frame().transpose()
  df2.reset_index(drop=True, inplace=True)
  df3.reset_index(drop=True, inplace=True)
  df2 = pd.concat([df2,df3],axis=1)
df37 = df2
df37
# print(df1)
for j in range(100):
  df = pd.DataFrame(aggregation_rules[j]).drop([17],axis=1)
  # df1 = pd.DataFrame(aggregation_rules[1]).drop([17],axis=1)

  df2 = df.iloc[0,:].to_frame().transpose()

  for i in range(1,52):
    df3 = df.iloc[i,:].to_frame().transpose()
    df2.reset_index(drop=True, inplace=True)
    df3.reset_index(drop=True, inplace=True)
    df2 = pd.concat([df2,df3],axis=1)
  df38 = df2
  # df38
  # print(df1)
  df37 = pd.concat([df37,df38],axis=0)
df37
final_rule2 = df37.iloc[1:101,:]

In [ ]:
final_rule2.head(20)
final_rule2.sum(axis=0)

0       5.0
1       4.0
2       9.0
3      10.0
4      10.0
      ...  
16    100.0
18     86.0
19      0.0
20    100.0
21      0.0
Length: 1092, dtype: float64

In [ ]:
final_rule2.to_csv('final_rule2.csv')


#CardsRed Cards

Diamond: 1 (0001)
Spades: 2 (0010)
Hearts: 3 (0100)
clubs: 4 (1000)

Hears and diamonds (1 and 3)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
aggregation_rules = []

for i in range(100):
  deck = []
 


  # creating instance of one-hot-encoder
  enc = OneHotEncoder(handle_unknown='ignore')
  counter = 0

  for suite in range (1,5):
    set = []
    for card_num in range (1,14):
      if card_num > 10:
        face = 1
      else:
        face = 0
      if suite%2 == 1:
        odd = 3
      else:
        odd = 2
      set.append([card_num,suite,face,odd])
    deck.extend(set)


  deck_duplicate = list.copy(deck)

  multiple = []
  multiple.clear()

  for i in range(30):
    multiple.append(random.choice(deck_duplicate))
    deck_duplicate.remove(multiple[-1])

  for j in range (len(multiple)):
    if multiple[j][3] == 2:
      multiple[j][3] = 1



  for note in deck_duplicate:
    note[3] = 2

  multiple.extend(deck_duplicate)

  #print(multiple)


  enc.fit(multiple)
  

  aggregation_rules.append(enc.transform(multiple).toarray())

#print(master)
#aggregation_rules.append(master)   

print(aggregation_rules[0])


    







[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [ ]:
pd.DataFrame(aggregation_rules[0])

0    1    2    3    4    5    6   ...   15   16   17   18   19   20   21
0   0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  1.0
2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  0.0  1.0
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  1.0  0.0  0.0
4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
5   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  1.0
6   0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  1.0
9   1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
10  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0
11  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
12  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  1.0
13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0
14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  1.0
15  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0  1.0  0.0  0.0  1.0
16  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0
17  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0  1.0  0.0  0.0  1.0
18  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  0.0  1.0
19  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  1.0  1.0  0.0  0.0
20  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0  1.0  0.0  0.0  0.0  1.0
21  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  0.0  1.0
22  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
23  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  1.0  1.0  0.0  0.0
24  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  0.0  1.0
25  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0
26  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  0.0  1.0
27  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  1.0
28  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  0.0  1.0
29  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  1.0
30  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
31  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
32  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
33  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  0.0  1.0  0.0
34  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  0.0  1.0  0.0
35  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  0.0  1.0  0.0
36  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
37  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
38  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
39  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
40  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  0.0  1.0  0.0
41  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  0.0  1.0  0.0
42  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  1.0  0.0
43  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  1.0  0.0
44  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  0.0  1.0  0.0
45  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0  1.0  0.0  1.0  0.0
46  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  0.0  1.0  0.0
47  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  0.0  1.0  0.0
48  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  1.0  1.0  0.0  0.0  1.0  0.0
49  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  1.0  1.0  0.0  0.0  1.0  0.0
50  0.0  0.0  0.0  0.0  0.0

In [ ]:
df = pd.DataFrame(aggregation_rules[0]).drop([17],axis=1)

df2 = df.iloc[0,:].to_frame().transpose()

for i in range(1,52):
  df3 = df.iloc[i,:].to_frame().transpose()
  df2.reset_index(drop=True, inplace=True)
  df3.reset_index(drop=True, inplace=True)
  df2 = pd.concat([df2,df3],axis=1)
df37 = df2
df37
# print(df1)
for j in range(100):
  df = pd.DataFrame(aggregation_rules[j]).drop([17],axis=1)
  # df1 = pd.DataFrame(aggregation_rules[1]).drop([17],axis=1)

  df2 = df.iloc[0,:].to_frame().transpose()

  for i in range(1,52):
    df3 = df.iloc[i,:].to_frame().transpose()
    df2.reset_index(drop=True, inplace=True)
    df3.reset_index(drop=True, inplace=True)
    df2 = pd.concat([df2,df3],axis=1)
  df38 = df2
  # df38
  # print(df1)
  df37 = pd.concat([df37,df38],axis=0)
df37
final_rule3 = df37.iloc[1:101,:]

In [ ]:
final_rule3.head(20)

0    1    2    3    4    5    6   ...   11   12   13   14   15   16   18
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  1.0  0.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  1.0  0.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  1.0  0.0  0.0
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  1.0  0.0  1.0  0.0  0.0
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0
0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.0

[20 rows x 936 columns]

#Black cards 

Diamond: 1
Spades: 2
Hearts: 3
clubs: 4

spades and clubs (2 and 4)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
aggregation_rules = []

for i in range(100):
  deck = []
 


  # creating instance of one-hot-encoder
  enc = OneHotEncoder(handle_unknown='ignore')
  counter = 0

  for suite in range (1,5):
    set = []
    for card_num in range (1,14):
      if card_num > 10:
        face = 1
      else:
        face = 0
      if suite%2 == 0:
        black = 3
      else:
        black = 2
      set.append([card_num,suite,face,black])
    deck.extend(set)


  deck_duplicate = list.copy(deck)

  multiple = []
  multiple.clear()

  for i in range(30):
    multiple.append(random.choice(deck_duplicate))
    deck_duplicate.remove(multiple[-1])

  for j in range (len(multiple)):
    if multiple[j][3] == 2:
      multiple[j][3] = 1



  for note in deck_duplicate:
    note[3] = 2

  multiple.extend(deck_duplicate)

  #print(multiple)


  enc.fit(multiple)
  

  aggregation_rules.append(enc.transform(multiple).toarray())

#print(master)
#aggregation_rules.append(master)   

print(aggregation_rules[0])


    







[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [ ]:
df = pd.DataFrame(aggregation_rules[0]).drop([17],axis=1)

df2 = df.iloc[0,:].to_frame().transpose()

for i in range(1,52):
  df3 = df.iloc[i,:].to_frame().transpose()
  df2.reset_index(drop=True, inplace=True)
  df3.reset_index(drop=True, inplace=True)
  df2 = pd.concat([df2,df3],axis=1)
df37 = df2
df37
# print(df1)
for j in range(100):
  df = pd.DataFrame(aggregation_rules[j]).drop([17],axis=1)
  # df1 = pd.DataFrame(aggregation_rules[1]).drop([17],axis=1)

  df2 = df.iloc[0,:].to_frame().transpose()

  for i in range(1,52):
    df3 = df.iloc[i,:].to_frame().transpose()
    df2.reset_index(drop=True, inplace=True)
    df3.reset_index(drop=True, inplace=True)
    df2 = pd.concat([df2,df3],axis=1)
  df38 = df2
  # df38
  # print(df1)
  df37 = pd.concat([df37,df38],axis=0)
df37
final_rule4 = df37.iloc[1:101,:]

#prime numbers
2,5,7,11,13

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
aggregation_rules = []

for i in range(100):
  deck = []
 


  # creating instance of one-hot-encoder
  enc = OneHotEncoder(handle_unknown='ignore')
  counter = 0

  for suite in range (1,5):
    set = []
    for card_num in range (1,14):
        if card_num >10:
          face = 1
        else:
          face = 0
        if card_num ==2 or (card_num%2 == 1 and not card_num== 9 and not card_num ==1):
          prime = 3
        else:
          prime = 2
        set.append([card_num,suite,face,prime])
    deck.extend(set)

  deck_duplicate = list.copy(deck)

  multiple = []
  multiple.clear()

  for i in range(30):
    multiple.append(random.choice(deck_duplicate))
    deck_duplicate.remove(multiple[-1])

  for j in range (len(multiple)):
    if multiple[j][3] == 2:
      multiple[j][3] = 1



  for note in deck_duplicate:
    note[3] = 2

  multiple.extend(deck_duplicate)

  #print(multiple)


  enc.fit(multiple)
  

  aggregation_rules.append(enc.transform(multiple).toarray())

#print(master)
#aggregation_rules.append(master)   

print(aggregation_rules[0])


    







[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [ ]:
aggregation_rules[0]

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [ ]:
df = pd.DataFrame(aggregation_rules[0]).drop([17],axis=1)

df2 = df.iloc[0,:].to_frame().transpose()

for i in range(1,52):
  df3 = df.iloc[i,:].to_frame().transpose()
  df2.reset_index(drop=True, inplace=True)
  df3.reset_index(drop=True, inplace=True)
  df2 = pd.concat([df2,df3],axis=1)
df37 = df2
df37
# print(df1)
for j in range(100):
  df = pd.DataFrame(aggregation_rules[j]).drop([17],axis=1)
  # df1 = pd.DataFrame(aggregation_rules[1]).drop([17],axis=1)

  df2 = df.iloc[0,:].to_frame().transpose()

  for i in range(1,52):
    df3 = df.iloc[i,:].to_frame().transpose()
    df2.reset_index(drop=True, inplace=True)
    df3.reset_index(drop=True, inplace=True)
    df2 = pd.concat([df2,df3],axis=1)
  df38 = df2
  # df38
  # print(df1)
  df37 = pd.concat([df37,df38],axis=0)
df37
final_rule5 = df37.iloc[1:101,:]

In [ ]:
final_rule5.to_csv('final_rule5.csv')

6th equation
#Red and even

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
aggregation_rules = []

for i in range(100):
  deck = []
 


  # creating instance of one-hot-encoder
  enc = OneHotEncoder(handle_unknown='ignore')
  counter = 0

  for suite in range (1,5):
    set = []
    for card_num in range (1,14):
        if card_num >10:
          face = 1
        else:
          face = 0
        if suite%2 ==1 and card_num%2 == 0:
          prime = 3
        else:
          prime = 2
        set.append([card_num,suite,face,prime])
    deck.extend(set)

  deck_duplicate = list.copy(deck)

  multiple = []
  multiple.clear()

  for i in range(30):
    multiple.append(random.choice(deck_duplicate))
    deck_duplicate.remove(multiple[-1])

  for j in range (len(multiple)):
    if multiple[j][3] == 2:
      multiple[j][3] = 1



  for note in deck_duplicate:
    note[3] = 2

  multiple.extend(deck_duplicate)

  #print(multiple)


  enc.fit(multiple)
  

  aggregation_rules.append(enc.transform(multiple).toarray())

#print(master)
#aggregation_rules.append(master)   

print(aggregation_rules[0])


    







[[1. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [ ]:
aggregation_rules[0]

array([[1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [ ]:
df = pd.DataFrame(aggregation_rules[0]).drop([17],axis=1)

df2 = df.iloc[0,:].to_frame().transpose()

for i in range(1,52):
  df3 = df.iloc[i,:].to_frame().transpose()
  df2.reset_index(drop=True, inplace=True)
  df3.reset_index(drop=True, inplace=True)
  df2 = pd.concat([df2,df3],axis=1)
df37 = df2
df37
# print(df1)
for j in range(100):
  df = pd.DataFrame(aggregation_rules[j]).drop([17],axis=1)
  # df1 = pd.DataFrame(aggregation_rules[1]).drop([17],axis=1)

  df2 = df.iloc[0,:].to_frame().transpose()

  for i in range(1,52):
    df3 = df.iloc[i,:].to_frame().transpose()
    df2.reset_index(drop=True, inplace=True)
    df3.reset_index(drop=True, inplace=True)
    df2 = pd.concat([df2,df3],axis=1)
  df38 = df2
  # df38
  # print(df1)
  df37 = pd.concat([df37,df38],axis=0)
df37
final_rule6 = df37.iloc[1:101,:]

In [ ]:
final_rule6.to_csv('final_rule6.csv')

In [ ]:
# convert list to ndarray 
import numpy as np 
from numpy import asarray
from numpy import savetxt

a = np.asarray(aggregation_rules) 
print(len(a))

newarr = a.reshape(100, 57)


# # sa
# # define data

savetxt('data.csv',yikes, delimiter=',')


5700


black and odd

In [ ]:

# save numpy array as csv file
from numpy import asarray
from numpy import savetxt
# define data
data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to csv file
savetxt('data.csv', data, delimiter=',')

In [ ]:
final_rule1.head()

0    1    2    3    4    5    6   ...   14   15   16   18   19   20   21
0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0

[5 rows x 1092 columns]

In [ ]:
final_rule2.head()

0    1    2    3    4    5    6   ...   14   15   16   18   19   20   21
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0

[5 rows x 1092 columns]

In [ ]:
final_rule3.head()

0    1    2    3    4    5    6   ...   14   15   16   18   19   20   21
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0

[5 rows x 1092 columns]

In [ ]:
final_rule4.head()

0    1    2    3    4    5    6   ...   14   15   16   18   19   20   21
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0

[5 rows x 1092 columns]

In [ ]:
final_rule5.head(40)

0    1    2    3    4    5    6   ...   14   15   16   18   19   20   21
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  1.0  0.0
0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  1.0  1.0  0.0  1.0  0.0

[40 rows x 1092 columns]

In [ ]:
for i in range(100):
  arr = np.append(arr,[6])
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3.

In [ ]:
arr.transpose()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3.

In [ ]:
arr = arr - 1
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2.

In [ ]:
import pickle
pickle.dump(arr,open('train_labels1.pkl', 'wb'))